Controllers films users
neobelov/java-filmorate pull request #1
Opened 2023-01-04 09:40 UTC by neobelov

Добавление объектов Film и User, а также контроллеров Spring к ним

2023-01-05 19:22 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохая работа, давай улучшим местами и будет зачёт

2023-01-05 19:22 UTC, krylov-sergey-sergeevich commented on mvnw
> +#!/bin/sh
Лучше файл добавить в гитигоре и удалить из pr

2023-01-05 19:22 UTC, krylov-sergey-sergeevich commented on HELP.md
> +# Getting Started
Лучше файл добавить в гитигоре и удалить из pr

2023-01-05 19:22 UTC, krylov-sergey-sergeevich commented on mvnw.cmd
> +@REM ----------------------------------------------------------------------------
Лучше файл добавить в гитигоре и удалить из pr

2023-01-05 19:22 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new ResourceNotFoundException("User for update is not found");
Ещё в тексте ошибки лучше указывать какой то id ненайденного объекта

2023-01-05 19:22 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ExceptionConfig.java
> +        throw new ValidationException(ex.getMessage());
Лучше кидать ошибку созданную самим разработчиком чем то что в фреймворке

2023-01-05 19:22 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (getReleaseDate().isBefore(LocalDate.of(1895, 12,28))) {
LocalDate.of(1895, 12,28) Это бы я вынес в класс констант

2023-01-05 20:24 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ExceptionConfig.java
> +        throw new ValidationException(ex.getMessage());
Сергей, привет! Эту ошибку валидации кидает фреймворк при использовании аннотации @Valid, которую в доп задании просят использовать. Я ее перевел на свою ошибку как раз. Как нужно переделать, не совсем понял?

2023-01-07 14:29 UTC, krylov-sergey-sergeevich approved these changes
Привет, все хорошо - зачет!

По пути к следующему дз добавь пж во всех методах контроллеров логирование

2023-01-07 14:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ExceptionConfig.java
> +        throw new ValidationException(ex.getMessage());
Все верно, мне показалось что тут бросалась не твоя ошибка, а из фреймворка

2023-01-07 15:26 UTC, merged