Add friends likes
neobelov/java-filmorate pull request #3
Opened 2023-01-08 13:51 UTC by neobelov

2023-01-09 18:52 UTC, krylov-sergey-sergeevich requested changes
Привет, работа сделана хорошо, есть маленькие недочеты поправь и будет зачет!

2023-01-09 18:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequiredArgsConstructor(onConstructor = @__(@Autowired))
А без (onConstructor = @__(@Autowired)) не работает?

2023-01-09 18:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@Valid @RequestBody Film film) {return filmStorage.update(film);}
В одну строку свернулось, давай развернем

2023-01-09 18:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/common/InMemoryStorage.java
> +import java.util.Map;
Пустую строку

2023-01-09 18:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/common/InMemoryStorage.java
> +public class InMemoryStorage<T extends StorageObject> implements Storage<T> {
Красиво сделано)

2023-01-09 18:52 UTC, krylov-sergey-sergeevich commented on src/main/resources/application.properties
> +logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
А напомни это для чего? Впервые вроде вижу такой параметр (ну не впервые, но студенты вроде не использовали)

2023-01-09 18:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceClass.java
> +public class FilmServiceClass implements FilmService {
Плохое название, надо такие классы называть FilmServiceImpl и аналогично похожие

2023-01-09 18:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceClass.java
> +public class UserServiceClass implements UserService {
Переименовать

2023-01-09 19:27 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequiredArgsConstructor(onConstructor = @__(@Autowired))
Почему-то не работает, да, пришлось так сделать

2023-01-09 19:34 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@Valid @RequestBody Film film) {return filmStorage.update(film);}
Хорошо, исправил везде, где такое было

2023-01-09 19:34 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/common/InMemoryStorage.java
> +import java.util.Map;
Принято

2023-01-09 19:35 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/storage/common/InMemoryStorage.java
> +public class InMemoryStorage<T extends StorageObject> implements Storage<T> {
Спасибо:)

2023-01-09 19:37 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceClass.java
> +public class FilmServiceClass implements FilmService {
Принято

2023-01-09 19:37 UTC, neobelov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceClass.java
> +public class UserServiceClass implements UserService {
Принято

2023-01-10 06:26 UTC, krylov-sergey-sergeevich approved these changes
Привет, все отлично, зачет

2023-01-10 06:27 UTC, merged